/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1lNwALh5LAw
 */
import {useState} from 'react'
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ConfigForm() {

  const getOpenAIKey = () => {
    const key = localStorage.getItem("openai-key");
    return (key === null) ? "" : key;
  }

  const saveOpenAIKey = (key) => {
    localStorage.setItem("openai-key", key);
  }

  const [openAIKey, setOpenAIKey] = useState(getOpenAIKey())

  return (
    (
      <div className="flex justify-center">
        <Card className="w-full max-w-md p-8 space-y-4">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-center">OpenAI API Key</CardTitle>
            <CardDescription className="text-center">Please enter your OpenAI API key below.</CardDescription>
          </CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={(e) => {e.preventDefault(); saveOpenAIKey(openAIKey);}}>
              <div className="space-y-2">
                <Label htmlFor="api-key">API Key</Label>
                <Input id="api-key" placeholder="Enter your API key" type="text" value={openAIKey} onChange={(e) => setOpenAIKey(e.target.value)} />
              </div>
              <Button className="w-full" type="submit">
                Save
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    )
  );
}
