/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7H0uW4LfPPE
 */


export function Wrapper({children}) {
  return (
    (<main className="flex items-center justify-center min-h-screen bg-gray-100">
      <div className="p-8 w-full max-w-screen">
        {children}
      </div>
    </main>)
  );
}
